version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "17:00"
      timezone: "Europe/Berlin"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "17:00"
      timezone: "Europe/Berlin"

  - package-ecosystem: "cargo"
    directory: "ext/snowflaked"
    schedule:
      interval: "daily"
      time: "17:00"
      timezone: "Europe/Berlin"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
      time: "17:00"
      timezone: "Europe/Berlin"
