[tools]
ruby = "4.0.1"
rust = { version = "1.93.1", profile = "default" }

[tasks]
test = [
  "bundle exec rake clobber",
  "bundle exec rake",
]

lint = [
  "bundle exec rubocop -A",
  "cargo clippy --manifest-path ext/snowflaked/Cargo.toml --fix --allow-dirty -- -D warnings",
  "cargo fmt --manifest-path ext/snowflaked/Cargo.toml",
]
